### PR TITLE
Improve the create account onboarding flow

### PR DESCRIPTION
**Pull request by MaxwellBo**
After

Screen Shot 2021-01-10 at 4 44 21 pm

Before

image

### CODE REVIEW

**Comment by MaxwellBo** [comment]
@kumar-ish fiddle around with this and see if it feels nice. I'm not sure if moving the 'Create account' button to a seperate step is a good thing 

On the one hand, it feels more inline with what people expect, and will allow us to ask questions when accounts are created like display name or marketing consent.

On the other hand, it will slow onboarding down by adding an extra click.

**Comment by MaxwellBo** [comment]
TODO: Fix breaking Cypress tests

**Comment by kumar-ish** [comment]
It looks a lot nicer, and feels more intuitive to me; at least this way account creation/login are somewhat separated too. LGTM

I tried amending it without a hacky pixel fix, but we still have to fix this floaty-ass cursed button somehow (and I think it might be beyond my ability to do so): image

**Review by kumar-ish — APPROVED** [review]

**Comment by MaxwellBo** [comment]
> I tried amending it without a hacky pixel fix, but we still have to fix this floaty-ass cursed button somehow (and I think it might be beyond my ability to do so):

Yeah, I tried fiddling around with it myself and it seems a little nightmarish :( I considered dropping it entirely and just flat out merging template creation into the setup screen, but I worry that that might negate the whole "oh cool it has committee templates" effect that you immediately see when you start to onboard .

**Pull request merged**
