### PR TITLE
Add default committee templates

### LINKED ISSUE #81: Committee Types
When creating a committee, along with selecting the Name, Topic, Chairpeople, and Conference, a Committee Type:

- ECOSOC
- UN General Assembly
- UNHCR
- UNHRC
- UNICEF
- UN Security Council
- WHO Executive Board

etc.

By selecting this, with the exception of the General Assembly, the committee members will be prepopulated in the Setup screen and the appropriate Majority rules will be set for the resolution (if #82) is implemented.

Example from https://session.muncommand.com/setup

image
image

### PR DESCRIPTION
**Pull request by kumar-ish**
Adds functionality as requested by and closes #81. There's more intelligent ways to initialise `STANDARD_COMMITTEES` and I'll fix that up later (open to suggestions though); there's also an unnecessary empty/no template provided value in `STANDARD_COMMITTEES`, which I'll just remove by adding a conditional @line#89 in `Onboard.tsx`. Some more countries may need to be added (e.g. as Sudan split into North & South Sudan) in order to satisfy the template countries (the African Union is incomplete at the moment) and more templates will need to be added for it to be a worthy feature.

### CODE REVIEW

**Comment by kumar-ish** [comment]
This is greattt (sorry for making you look at the spaghetti that was my code before). It looks like the Cypress error is coming from template being undefined (when there is no selection made, that is) since Firebase dosen't like that; adding a default (empty) string back to DEFAULT_COMMITTEE should fix it. We should also probably add a Cypress test for the dropdown as well.

**Comment by MaxwellBo** [comment]
@kumar-ish Good idea! Just did that then!

**Comment by MaxwellBo** [comment]
@kumar-ish can you undraft the PR?

**Comment by kumar-ish** [comment]
👌

**Pull request merged**
