### PR TITLE
Vite Migration

### PR DESCRIPTION
**Pull request by GeordieEK**
#### Description

Migration from `create-react-app` to `vite`

Includes move from `jest` to `vitest`
Includes move from `require()` to `import` syntax for `cypress v13+`

#### Motivation

Addresses #195

#### Testing

Fails as many Cypress tests as it did with CRA

### CODE REVIEW

**Comment by GeordieEK** [comment]
Can we remove this heroku buildpack from `app.json`?

```json
  "buildpacks": [
    {
      "url": "https://github.com/mars/create-react-app-buildpack"
    }
  ]
```

**Comment by MaxwellBo** [comment]
> Can we remove this heroku buildpack from app.json?

yep!

**Comment by MaxwellBo** [comment]
Let me figure out `Error: SentryCLI needs an authentication token. Please set env variable SENTRY_AUTH_TOKEN`

**Comment by MaxwellBo** [comment]
```
1:21:35 PM: Deploy site                                                   
1:21:35 PM: ────────────────────────────────────────────────────────────────
1:21:35 PM: ​
1:21:35 PM: Section completed: deploying
1:21:35 PM: ​
1:21:35 PM: Configuration error                                           
1:21:35 PM: ────────────────────────────────────────────────────────────────
1:21:35 PM: ​
1:21:35 PM:   Error message
1:21:35 PM:   Deploy did not succeed: Deploy directory 'build' does not exist
1:21:35 PM: ​
1:21:35 PM:   Resolved config
1:21:35 PM:   build:
1:21:35 PM:     command: yarn build
1:21:35 PM:     commandOrigin: ui
1:21:35 PM:     environment:
1:21:35 PM:       - CI
1:21:35 PM:       - REVIEW_ID
1:21:35 PM:     publish: /opt/build/repo/build
1:21:35 PM:     publishOrigin: ui
1:21:36 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
1:21:36 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
1:21:36 PM: Failing build: Failed to build site
```

**Comment by GeordieEK** [comment]
Fixed Netlify build

**Review by MaxwellBo — APPROVED** [review]

**Pull request merged**
